export { 
  bookCategoryReference,
  bookCategoryTagReference,
  blogTagReference,
  featureReference,
  guidedTourReference,
  guidedTourStepReference,
  memberOptionReference,
  movieTagReference,
  musicTagReference,
  poemCategoryReference,
  poemCategoryTagReference,
  showTagReference,
  supportEnvironment,
  supportFamily,
  supportIssue,
  supportResponse,
  supportAttachment,
  supportTeam,
  supportPerson,
  supportPersonIssue,
  threadTemplate,
  video,
  videoS3Credentials,
  videoTagReference,
  videoTag,
} from './global-schema-tables';
