export { 
  bookCategoryReference,
  bookCategoryTagReference,
  bookTerm,
  movieTagReference,
  musicTagReference,
  poemCategoryReference,
  poemCategoryTagReference,
  poemTerm,
  showTagReference,
  supportEnvironment,
  supportFamily,
  supportIssue,
  supportResponse,
  supportAttachment,
  supportTeam,
  supportPerson,
  supportPersonIssue,
  video,
  videoS3Credentials,
  videoTagReference,
  videoTag,
} from './global-schema-tables';
